spring:
  application:
    name: order-management
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=orders
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  redis:
    host= localhost
    port= 6379
