spring:
  application:
    name: order-management
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=orders
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  redis:
    host= localhost
    port= 6379
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs

