openapi: 3.0.3
info:
  title: Order Management API
  version: 1.0.0
  description: API для управления заказами
servers:
  - url: http://localhost:8080
    description: Локальный сервер разработки

paths:
  /orders/create:
    post:
      tags:
        - Orders
      summary: Создать новый заказ
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrdersEntity'
      responses:
        '200':
          description: Заказ успешно создан
          content:
            text/plain:
              schema:
                type: string
                example: "Success"

  /orders/find/{id}:
    get:
      tags:
        - Orders
      summary: Получить заказ по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Найденный заказ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrdersDto'
        '404':
          description: Заказ не найден

  /orders/findAll:
    get:
      tags:
        - Orders
      summary: Получить заказы по дате и минимальной сумме
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
            pattern: '^\d{8}$'
            example: "20231025"
        - name: minTotal
          in: query
          required: true
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: Список заказов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrdersDto'

  /orders/without-product:
    get:
      tags:
        - Orders
      summary: Получить заказы без указанного товара
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
            pattern: '^\d{8}$'
            example: "20230101"
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date
            pattern: '^\d{8}$'
            example: "20231231"
        - name: articleProduct
          in: query
          required: true
          schema:
            type: integer
            example: 12345
      responses:
        '200':
          description: Список заказов без указанного товара
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrdersDtoWithoutProduct'

components:
  schemas:
    OrdersEntity:
      type: object
      properties:
        orderNumber:
          type: string
          example: "ORD-123"
        totalOrderAmount:
          type: integer
          example: 1000
        orderDate:
          type: string
          format: date
          example: "2023-10-25"
        address:
          type: string
          example: "ул. Тестовая, 1"
        deliveryAddress:
          type: string
          example: "ул. Доставки, 5"
        paymentType:
          type: string
          example: "CARD"
        deliveryType:
          type: string
          example: "COURIER"
        ordersDetails:
          type: array
          items:
            $ref: '#/components/schemas/OrdersDetailsEntity'

    OrdersDetailsEntity:
      type: object
      properties:
        articleProduct:
          type: integer
          example: 1001
        nameProduct:
          type: string
          example: "Тестовый товар 1"
        quantity:
          type: integer
          example: 2
        unitCost:
          type: integer
          example: 300

    OrdersDto:
      type: object
      properties:
        id:
          type: integer
          example: 1
        orderNumber:
          type: string
          example: "ORD-123"
        totalOrderAmount:
          type: integer
          example: 1000
        orderDate:
          type: string
          format: date
          example: "2023-10-25"
        address:
          type: string
          example: "ул. Тестовая, 1"
        deliveryAddress:
          type: string
          example: "ул. Доставки, 5"
        paymentType:
          type: string
          example: "CARD"
        deliveryType:
          type: string
          example: "COURIER"

    OrdersDtoWithoutProduct:
      type: object
      properties:
        id:
          type: integer
          example: 1
        orderNumber:
          type: string
          example: "ORD-123"
        totalOrderAmount:
          type: integer
          example: 1000
        orderDate:
          type: string
          format: date
          example: "2023-10-25"
        address:
          type: string
          example: "ул. Тестовая, 1"
        deliveryAddress:
          type: string
          example: "ул. Доставки, 5"
        paymentType:
          type: string
          example: "CARD"
        deliveryType:
          type: string
          example: "COURIER"