create table ordersdetails
(
    id             integer generated by default as identity
        constraint ordersdetails_pk
            primary key,
    articleproduct integer,
    nameproduct    varchar(100),
    quantity       integer,
    unitcost       integer,
    idorders       integer not null
        constraint ordersdetails_orders_fk
            references orders
);